import { Box, Button, Stack } from "@mui/material";
import SettingsIcon from "@mui/icons-material/Settings";
import Head from "next/head";
import Typography from "@mui/material/Typography";
import styled from "@emotion/styled";
import Sidebar from "./components/Sidebar";
import Feed from "./components/Feed";
import RightBar from "./components/RightBar";
import Nav from "./components/nav";
export default function Home() {
  const CustomBtn = styled(Button)({
    background: "Red",
    color: "black",
    mx: "50px",
    "&:hover": {
      color: "red",
      background: "black",
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Nav></Nav>
        <Stack direction={"row"} spacing={2} justifyContent={"space-between"}>
          <Sidebar />
          <Feed />
          <RightBar />
        </Stack>
      </Box>
    </>
  );
}
